stages:
  - build
  - prepare
  - test
  - sast
  - review
  - deploy_stage
  - dast
  - deploy_dev
  - deploy_hml
  - deploy_prod

build:
  stage: build
  script:
  - sleep 1

prepare:
  stage: prepare
  script:
  - sleep 1

test_unit:
  stage: test
  script:
  - sleep 1

test_integration:
  stage: test
  script:
  - sleep 1

test_functional:
  stage: test
  script:
  - sleep 1

sast_bandit:
  stage: sast
  script:
  - sleep 1

sast_dependency_check:
  stage: sast
  script:
  - sleep 1

review_app:
  stage: review
  script:
  - sleep 1
  rules:
  - if: '$CI_MERGE_REQUEST_IID'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: stop_review_app

stop_review_app:
  stage: review
  script:
  - sleep 1
  when: manual
  rules:
  - if: '$CI_MERGE_REQUEST_IID'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

deploy_stage:
  stage: deploy_stage
  script:
  - sleep 1
  when: manual
  environment:
    name: stage

dast_zap:
  stage: dast
  script:
  - sleep 1
  needs:
  - job: deploy_stage
    optional: true

deploy_dev:
  stage: deploy_dev
  script:
  - sleep 1
  when: manual
  environment:
    name: dev

deploy_hml:
  stage: deploy_hml
  script:
  - sleep 1
  when: manual
  environment:
    name: hml

deploy_prod:
  stage: deploy_prod
  script:
  - sleep 1
  when: manual
  environment:
    name: production
