stages:
  - build
  - test_unit
  - test_integration
  - test_functional
  - deploy_dev
  - deploy_hml
  - deploy_prod
  - deploy # Adicionando a stage de deploy

variables:
  PYTHON_VERSION: "3.11-slim"
  VENV_PATH: ".venv"
  DOCKER_IMAGE_NAME: "task-manager"
  CI_REGISTRY: "192.168.98.10:8080" # Hostname e porta do seu registro Docker
  SECRET_KEY: $SECRET_KEY # Assume que SECRET_KEY está definido como variável secreta no GitLab CI
  BASE_URL: "http://localhost:8080" # URL da API para testes funcionais (ajuste se necessário)

cache:
  key: "venv-${CI_COMMIT_SHORT_SHA}"
  paths:
    - ${VENV_PATH}/

build:
  stage: build
  image: docker:20.10.21 # Imagem Docker
  services:
    - docker:dind
  script:
    - echo "Compilando a imagem Docker..."
    - PROJECT_PATH_LOWER=$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]')
    - IMAGE_TAG_FINAL="${CI_REGISTRY}/${PROJECT_PATH_LOWER}:${CI_COMMIT_SHORT_SHA}"
    - docker build --cache-from "$IMAGE_TAG_FINAL" --tag "$IMAGE_TAG_FINAL" .
    - echo "Pushing a imagem Docker..."
    - docker push "$IMAGE_TAG_FINAL"
  artifacts:
    paths:
      - ./

test_unit:
  stage: test_unit
  image: python:${PYTHON_VERSION}
  script:
    - echo "Executando testes unitários..."
    - python -m venv ${VENV_PATH}
    - source ${VENV_PATH}/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt -r requirements-dev.txt
    - pip install pytest pytest-cov
    - pytest --cov=todo_project --cov-report=xml:coverage.xml tests/unitary
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test_integration:
  stage: test_integration
  image: "${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA}" # Usando a imagem Docker construída
  variables:
    BASE_URL: "http://localhost:5000" # URL para os testes de integração (dentro do container isolado)
  script:
    - echo "Executando testes de integração em ambiente Docker..."
    - docker run --rm --name integration-tests -p 5000:5000 -e SECRET_KEY="$SECRET_KEY" "${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA}" python todo_project/run.py & # Executa em background
    - sleep 5 # Espera a aplicação iniciar
    - python -m venv ${VENV_PATH} # Criando um venv novamente para isolamento
    - source ${VENV_PATH}/bin/activate
    - pip install -r requirements.txt pytest requests
    - pytest tests/integration
    - docker stop integration-tests

test_functional:
  stage: test_functional
  image: "${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA}" # Usando a imagem Docker construída
  variables:
    BASE_URL: "http://localhost:8080" # URL da API para testes funcionais
  script:
    - echo "Executando testes funcionais (API)..."
    - python -m venv ${VENV_PATH}
    - source ${VENV_PATH}/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt pytest requests
    - cd tests/functional
    - pytest --base-url=${BASE_URL}

deploy_dev:
  stage: deploy_dev
  image: alpine/git # Uma imagem leve com Git para deploy
  only:
    - develop
  script:
    - echo "Iniciando deploy para o ambiente de desenvolvimento..."
    - echo "Simulando deploy da imagem ${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA} para o ambiente de desenvolvimento."
    - echo "Nenhuma ação de deploy real implementada."

deploy_hml:
  stage: deploy_hml
  image: alpine/git # Uma imagem leve com Git para deploy
  only:
    - hml
  script:
    - echo "Iniciando deploy para o ambiente de homologação (HML)..."
    - echo "Simulando deploy da imagem ${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA} para o ambiente de homologação."
    - echo "Nenhuma ação de deploy real implementada."

deploy_prod:
  stage: deploy_prod
  image: alpine/git # Uma imagem leve com Git para deploy
  only:
    - prod
  script:
    - echo "Iniciando deploy para o ambiente de produção..."
    - echo "Simulando deploy da imagem ${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA} para o ambiente de produção."
    - echo "Nenhuma ação de deploy real implementada."

deploy: # Adicionando o job de deploy
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - docker-stable # Certifique-se de usar a tag que você definiu para o runner
  before_script:
    - echo "Remove anterior"
    - PORT_CONTAINERS=$(docker ps --filter "publish=8081" -q)
    - echo "$PORT_CONTAINERS" # Adicionadas aspas para evitar problemas com strings vazias
    - if [ -n "$PORT_CONTAINERS" ]; then
        docker stop "$PORT_CONTAINERS"
        docker rm "$PORT_CONTAINERS"
        sleep 5
      fi
  script:
    - echo "Deploying the app"
    - docker run -d -p 8081:8080 "${CI_REGISTRY}/$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]'):${CI_COMMIT_SHORT_SHA}" # Usando a variável IMAGE_TAG com aspas
