version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager
    container_name: task-manager-container
    ports:
      - "8080:5000"
    volumes:
      - task_manager_data:/app/todo_project/todo_project/site.db
    environment:
      SECRET_KEY: ${SECRET_KEY} # Certifique-se de definir essa variável no seu ambiente
    restart: always

volumes:
  task_manager_data:

